# Generated by Django 4.2.4 on 2023-08-20 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idealo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='subscription_type',
            field=models.TextField(default=None),
        ),
    ]
