# Generated by Django 4.2.4 on 2023-08-20 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idealo_app', '0002_apikey_subscription_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='subscription_type',
            field=models.CharField(max_length=8),
        ),
    ]
