# Generated by Django 4.2.4 on 2023-08-20 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('idealo_app', '0003_alter_apikey_subscription_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
