# Generated by Django 4.2.4 on 2023-08-20 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idealo_app', '0005_alter_apikey_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apikey',
            name='user',
        ),
    ]
