# Generated by Django 4.2.4 on 2023-08-21 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idealo_app', '0007_remove_apikey_key_apikey_requests_left_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apikey',
            old_name='timestamp',
            new_name='expiry',
        ),
    ]
