# Generated by Django 4.2.4 on 2023-08-21 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idealo_app', '0009_apikey_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='requests_left',
            field=models.IntegerField(default=1000),
        ),
    ]
